---
# handlers file for k8s-base
- name: save k8s details
  copy: 
    content: >
      {
        "k8s_version": "{{ k8s_version.stdout }}",
        "k8s_install_date": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/k8s.fact

  become: yes
